In [1]:
import torch

c:\Software\Anaconda\envs\ML\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3, 4)

tensor([[0.7034, 0.8213, 0.7947, 0.1825],
        [0.2668, 0.7652, 0.9034, 0.9431],
        [0.4315, 0.1405, 0.5158, 0.0059]])

In [5]:
torch.randint(0, 10, (2, 3))

tensor([[6, 8, 2],
        [5, 3, 5]])

In [6]:
torch.randn(3, 4)

tensor([[-1.2616, -1.3032, -0.9507, -0.4264],
        [ 1.6260, -0.6063,  2.2875,  0.3296],
        [-1.0551,  1.2840,  1.2663,  0.4621]])

In [8]:
a = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]])

In [9]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
b = torch.rand_like(a, dtype=float)

In [11]:
b

tensor([[0.0803, 0.2874],
        [0.0758, 0.7117],
        [0.6079, 0.2982]], dtype=torch.float64)

In [12]:
b.shape

torch.Size([3, 2])

In [14]:
b.size()

torch.Size([3, 2])

In [15]:
# view相当于reshape
c = b.view(6)
c

tensor([0.0803, 0.2874, 0.0758, 0.7117, 0.6079, 0.2982], dtype=torch.float64)

In [16]:
c.shape

torch.Size([6])

In [17]:
d = b.view(2, 3)
d

tensor([[0.0803, 0.2874, 0.0758],
        [0.7117, 0.6079, 0.2982]], dtype=torch.float64)

In [18]:
d = d.reshape(6)
d

tensor([0.0803, 0.2874, 0.0758, 0.7117, 0.6079, 0.2982], dtype=torch.float64)

In [20]:
d[1].item()

0.2873529509980949

In [21]:
import numpy as np

In [22]:
np.array(d)

array([0.08033849, 0.28735295, 0.07584767, 0.71174406, 0.60789554,
       0.29815028])

In [23]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [24]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)