In [1]:
import torch

In [2]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3,4)

tensor([[4.9828e-01, 1.1043e-01, 4.8902e-01, 3.6291e-01],
        [9.5399e-01, 4.0034e-01, 7.2264e-01, 3.1182e-01],
        [1.2877e-01, 8.0676e-01, 8.0019e-04, 8.5096e-01]])

In [5]:
torch.randint(0,10,(2,3))

tensor([[6, 8, 7],
        [7, 7, 0]])

In [6]:
torch.randn(3,4)

tensor([[ 0.9459, -0.0176, -0.2926, -0.1742],
        [ 1.5522,  0.7279,  0.1983, -0.5494],
        [-0.3978,  0.9780, -0.1995, -0.1070]])

In [7]:
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

In [8]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
b = torch.rand_like(a, dtype=float)
b

tensor([[0.0328, 0.7155],
        [0.7128, 0.7107],
        [0.7301, 0.4723]], dtype=torch.float64)

In [10]:
# 查看数据的形状
print(b.shape)
print(b.size())

torch.Size([3, 2])
torch.Size([3, 2])


In [12]:
# view相当于reshape
c = b.view(6)
c

tensor([0.0328, 0.7155, 0.7128, 0.7107, 0.7301, 0.4723], dtype=torch.float64)

In [13]:
c.shape

torch.Size([6])

In [14]:
d = b.view(2,3)
d

tensor([[0.0328, 0.7155, 0.7128],
        [0.7107, 0.7301, 0.4723]], dtype=torch.float64)

In [15]:
d = d.reshape(6)
d

tensor([0.0328, 0.7155, 0.7128, 0.7107, 0.7301, 0.4723], dtype=torch.float64)

In [16]:
d[1]

tensor(0.7155, dtype=torch.float64)

In [17]:
d[1].item()

0.7154563873659074

In [19]:
import numpy as np

In [20]:
e = np.array(d)
e

array([0.0328271 , 0.71545639, 0.71275876, 0.71065724, 0.73006676,
       0.47229271])

In [21]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [22]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)