In [2]:
import torch

In [3]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[4, 1, 2],
        [3, 2, 4]])
tensor([[1, 2, 2],
        [1, 1, 3]])


In [4]:
a + b

tensor([[5, 3, 4],
        [4, 3, 7]])

In [5]:
torch.add(a,b)

tensor([[5, 3, 4],
        [4, 3, 7]])

In [6]:
result = torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[5., 3., 4.],
        [4., 3., 7.]])

In [7]:
result

tensor([[5., 3., 4.],
        [4., 3., 7.]])

In [8]:
# a = a + b
# 注意 任何使张量tensor会发生变化的操作都有一个前缀'_'，例如：a.add_(),b.sub_()
a.add_(b)
a

tensor([[5, 3, 4],
        [4, 3, 7]])

In [9]:
a - b

tensor([[4, 1, 2],
        [3, 2, 4]])

In [10]:
a * b

tensor([[ 5,  6,  8],
        [ 4,  3, 21]])

In [11]:
a / b

tensor([[5.0000, 1.5000, 2.0000],
        [4.0000, 3.0000, 2.3333]])

In [12]:
# 取余数
a % b

tensor([[0, 1, 0],
        [0, 0, 1]])

In [13]:
# 取整
a // b

tensor([[5, 1, 2],
        [4, 3, 2]])

In [14]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
a

tensor([[5, 3, 4],
        [4, 3, 7]])

In [16]:
torch.matmul(a,tensor)

RuntimeError: expected scalar type Long but found Float

In [17]:
a.dtype

torch.int64

In [18]:
tensor.dtype

torch.float32

In [19]:
a = a.float()
a.dtype

torch.float32

In [20]:
torch.matmul(a,tensor) # 2*3 3*5 = 2*5

tensor([[12., 12., 12., 12., 12.],
        [14., 14., 14., 14., 14.]])

In [21]:
a.T

tensor([[5., 4.],
        [3., 3.],
        [4., 7.]])