In [2]:
import torch

In [3]:
sample = torch.rand(3,2)

In [4]:
sample

tensor([[0.3860, 0.8405],
        [0.2176, 0.1118],
        [0.8619, 0.1684]])

In [5]:
torch.sum(sample)

tensor(2.5862)

In [6]:
torch.min(sample)

tensor(0.1118)

In [7]:
torch.max(sample)

tensor(0.8619)

In [8]:
# 求最小值所在的位置（索引）
torch.argmin(sample)

tensor(3)

In [9]:
# 求最大值所在的位置（索引）
torch.argmax(sample)

tensor(4)

In [10]:
torch.mean(sample)

tensor(0.4310)

In [11]:
torch.median(sample)

tensor(0.2176)

In [12]:
torch.sqrt(sample)

tensor([[0.6213, 0.9168],
        [0.4665, 0.3343],
        [0.9284, 0.4104]])

In [13]:
sample ** 2

tensor([[0.1490, 0.7065],
        [0.0473, 0.0125],
        [0.7428, 0.0284]])